sonar.projectKey=finalhostel
sonar.projectName=finalhostel
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.inclusions=server.js,recommendation-engine.js,public/**/*.js,scripts/**/*.js
sonar.exclusions=node_modules/**,.github/**,coverage/**,public/**/*.html,README.md,DOCKER_SETUP.md
